# Menú del shaderpack. Los perfiles se añadirán cuando las opciones finales existan en fase 5.
screen = [PRESETS] [LIGHTING] [RAY_TRACING] [SHADOWS] [SKY_CLOUDS] [FOG_ATMOSPHERE] [WATER] [WEATHER] [DIMENSIONS] [POST_PROCESSING] [ANIMATIONS] [COLORS] [DEBUG]

screen.PRESETS = <profile>
screen.LIGHTING = <empty>
screen.RAY_TRACING = <empty>
screen.SHADOWS = SHADOW_FILTER_MODE SHADOW_QUALITY SHADOW_STRENGTH SHADOW_PENUMBRA SHADOW_DISTORTION shadowMapResolution shadowDistance
screen.SKY_CLOUDS = <empty>
screen.FOG_ATMOSPHERE = <empty>
screen.WATER = <empty>
screen.WEATHER = <empty>
screen.DIMENSIONS = <empty>
screen.POST_PROCESSING = <empty>
screen.ANIMATIONS = <empty>
screen.COLORS = <empty>
screen.DEBUG = <empty>

sliders = SHADOW_STRENGTH SHADOW_PENUMBRA SHADOW_DISTORTION shadowMapResolution shadowDistance
